import { Footer, NavbarContainer } from '@/components';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import ToastProvider from '@/providers/toast-provider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'LMS - Edtech tools',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <TankstackProviders> */}
        <ToastProvider duration={1500} />
        <div className="relative flex flex-col min-h-screen">
          <NavbarContainer />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
        {/* </TankstackProviders> */}
      </body>
    </html>
  );
}
